# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8cbf6b46ddcfd7e8a5cdc8d812b7a446139f33252f6ae79c65b98c0e781d67331d512363d04e0d8a747ca7e924f9d4f424120dce69fc671c0181e17575da1bef

test:
  secret_key_base: a6357b7c89dd05e62b14df668f9329d8d5d26c6f6841d1e1ebaa70dc6031f9317eaabfa50e399e52bbb168c7cf9d74e72fefc769ab61290aeca064ecffddc979

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
